name = 'Plain'
license = 'MIT'
description = 'Theme description'

# The home page of the theme, where the source can be found
homepage = 'https://github.com/sshine/plain-hugo-theme'

# If you have a running demo of the theme
demosite = 'https://nix.tools'

# Taxonomy terms
#tags = ['blog', 'company']
#features = ['some', 'awesome', 'features']

# If the theme has a single author
[author]
  name = 'Simon Shine'
  homepage = 'https://simonshine.dk'
